Decoupling Bonfire component name and component name
gbenhaim/tekton-insights pull request #25
Opened 2024-04-16 16:22 UTC by dscervantes

Sometimes the component name can be different from the bonfire component name

2024-04-16 20:19 UTC, dscervantes commented
@gbenhaim @ernesgonzalez33 can i get a review on this :)

2024-04-17 06:53 UTC, ernesgonzalez33 commented
/test

2024-04-17 07:23 UTC, ernesgonzalez33 commented
@dscervantes @gbenhaim please correct me if I'm wrong, but I think this is introducing a breaking change.

If we don't add a default value to the pipeline parameter, that would mean that all pipelines using this new pipeline will fail starting for now since they are not using the new parameter.

Do we want to continue supporting COMPONENT_NAME for those that has the same name of the component in Konflux and in clowder? Because I also see here that now the component depends only on this new variable: https://github.com/gbenhaim/cicd-tools/blob/main/bin/parse-snapshot.py#L61

2024-04-17 07:30 UTC, ernesgonzalez33 commented
> @dscervantes @gbenhaim please correct me if I'm wrong, but I think this is introducing a breaking change.
> 
> If we don't add a default value to the pipeline parameter, that would mean that all pipelines using this new pipeline will fail starting for now since they are not using the new parameter.
> 
> Do we want to continue supporting COMPONENT_NAME for those that has the same name of the component in Konflux and in clowder? Because I also see here that now the component depends only on this new variable: https://github.com/gbenhaim/cicd-tools/blob/main/bin/parse-snapshot.py#L61

Ok, Now I see that it is still taking `component.name` as default if the new variable doesn't exits. That would mean that @dscervantes you should add a default value of `""` to the new parameter in the pipeline

2024-04-17 07:34 UTC, ernesgonzalez33 requested changes

2024-04-17 07:34 UTC, ernesgonzalez33 commented on pipelines/basic.yaml
> +      description: name of the app-sre component name
Add a default value of `""` to make the parameter optional

2024-04-17 07:34 UTC, ernesgonzalez33 commented on tasks/deploy.yaml
> +      description: name of the app-sre component name
Add a default value of "" to make the parameter optional

2024-04-17 07:34 UTC, ernesgonzalez33 commented on tasks/run-cji-smoke-test.yaml
> +      description: name of the app-sre component name
Add a default value of "" to make the parameter optional

2024-04-17 07:34 UTC, ernesgonzalez33 commented on tasks/run-cji-smoke-test.yaml
For this to work, the function here needs to be updated as well with the new parameter: https://github.com/gbenhaim/cicd-tools/blob/main/bin/deploy-iqe-cji.sh

2024-04-17 07:43 UTC, ernesgonzalez33 commented on tasks/run-cji-smoke-test.yaml
Being worked on it here: https://github.com/gbenhaim/cicd-tools/pull/15

2024-04-18 02:40 UTC, dscervantes commented
@ernesgonzalez33 Can you let me know when the other PR is able to be merged https://github.com/gbenhaim/cicd-tools/pull/15 thanks! fixed the other defaults

2024-04-18 09:39 UTC, ernesgonzalez33 commented
/test

2024-04-18 19:17 UTC, dscervantes commented
/test

2024-04-18 19:51 UTC, dscervantes reviewed
done

2024-04-18 20:09 UTC, ernesgonzalez33 commented
/test

2024-04-19 01:06 UTC, dscervantes commented
/test

2024-04-19 04:54 UTC, ernesgonzalez33 commented
/test

2024-04-19 13:27 UTC, dscervantes commented
@ernesgonzalez33 can I get an approval? It doesn't let me test without it

2024-04-19 13:42 UTC, ernesgonzalez33 commented
@dscervantes it was already tested. Failed again: https://github.com/gbenhaim/tekton-insights/pull/25/checks?check_run_id=24004374506. I think the issue is cicd-tools. I'll check it today

2024-04-19 15:35 UTC, ernesgonzalez33 requested changes

2024-04-19 15:35 UTC, ernesgonzalez33 commented on tasks/run-cji-smoke-test.yaml
> +          value: $(BONFIRE_COMPONENT_NAME)
this should be `$(params.BONFIRE_COMPONENT_NAME)`

2024-04-19 16:00 UTC, ernesgonzalez33 approved these changes

2024-04-19 16:10 UTC, merged